[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tic_tac_toe = "HL3c9emYeed8UUv8FKKarXBK5yjNaeQjJCpThEBfMYV5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
